import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import {
    Plus, Trash2, Download, Upload, Key, Link2, X, Copy,
    Database, FileJson, FileCode, LayoutGrid, MousePointer2,
    GitBranch, Save, RotateCcw, StickyNote, ArrowRight, Sparkles,
    Send, KeyRound,
} from 'lucide-react';
import './SchemaDesigner.css';

const STORAGE_KEY = 'shakti_dev_schema_v1';
const TYPES = [
    'UUID', 'SERIAL', 'BIGSERIAL', 'INT', 'BIGINT', 'SMALLINT',
    'TEXT', 'VARCHAR(255)', 'VARCHAR(64)', 'CHAR(2)',
    'BOOLEAN', 'TIMESTAMPTZ', 'TIMESTAMP', 'DATE', 'TIME',
    'NUMERIC', 'REAL', 'DOUBLE PRECISION',
    'JSON', 'JSONB', 'BYTEA', 'ENUM',
];

const uid = () => Math.random().toString(36).slice(2, 9);

const defaultColumn = () => ({
    id: uid(),
    name: 'column_name',
    type: 'TEXT',
    pk: false,
    nn: false,
    uq: false,
});

const seedSchema = () => ({
    tables: [
        {
            id: 't_users',
            name: 'users',
            x: 80,
            y: 80,
            color: '#1f1f1f',
            columns: [
                { id: 'c_u_id', name: 'id', type: 'UUID', pk: true, nn: true, uq: true },
                { id: 'c_u_email', name: 'email', type: 'VARCHAR(255)', pk: false, nn: true, uq: true },
                { id: 'c_u_name', name: 'name', type: 'VARCHAR(255)', pk: false, nn: false, uq: false },
                { id: 'c_u_created', name: 'created_at', type: 'TIMESTAMPTZ', pk: false, nn: true, uq: false },
            ],
        },
        {
            id: 't_opt',
            name: 'optimizations',
            x: 480,
            y: 80,
            color: '#c2410c',
            columns: [
                { id: 'c_o_id', name: 'id', type: 'UUID', pk: true, nn: true, uq: true },
                { id: 'c_o_uid', name: 'user_id', type: 'UUID', pk: false, nn: true, uq: false },
                { id: 'c_o_mode', name: 'mode', type: 'VARCHAR(64)', pk: false, nn: true, uq: false },
                { id: 'c_o_title', name: 'new_title', type: 'TEXT', pk: false, nn: false, uq: false },
                { id: 'c_o_desc', name: 'new_description', type: 'TEXT', pk: false, nn: false, uq: false },
                { id: 'c_o_created', name: 'created_at', type: 'TIMESTAMPTZ', pk: false, nn: true, uq: false },
            ],
        },
    ],
    relations: [
        {
            id: 'r_opt_uid',
            fromTable: 't_opt',
            fromColumn: 'c_o_uid',
            toTable: 't_users',
            toColumn: 'c_u_id',
            onDelete: 'CASCADE',
        },
    ],
    notes: [],
    arrows: [],
});

const loadSchema = () => {
    try {
        const raw = localStorage.getItem(STORAGE_KEY);
        if (raw) {
            const parsed = JSON.parse(raw);
            return {
                tables: parsed.tables || [],
                relations: parsed.relations || [],
                notes: parsed.notes || [],
                arrows: parsed.arrows || [],
            };
        }
    } catch { /* ignore */ }
    return seedSchema();
};

const NOTE_COLORS = ['#fef3c7', '#dbeafe', '#dcfce7', '#fce7f3', '#e9d5ff', '#fed7aa'];
const AI_KEY_STORAGE = 'shakti_openrouter_key';
const AI_MODEL_STORAGE = 'shakti_ai_model';
const DEFAULT_AI_MODEL = 'openai/gpt-4o-mini';

/* Approx height so arrows can anchor to table center */
const tableHeight = (t) => HEADER_HEIGHT + (t.columns?.length || 0) * ROW_HEIGHT + 30;
const tableCenter = (t) => ({ x: t.x + tableW(t) / 2, y: t.y + tableHeight(t) / 2 });
const noteCenter = (n) => ({ x: n.x + (n.width || 200) / 2, y: n.y + (n.height || 120) / 2 });

const elementAnchor = (schema, kind, id) => {
    if (kind === 'table') {
        const t = schema.tables.find(x => x.id === id);
        return t ? tableCenter(t) : null;
    }
    if (kind === 'note') {
        const n = schema.notes.find(x => x.id === id);
        return n ? noteCenter(n) : null;
    }
    return null;
};

/* ─── SQL Export ─────────────────────────────────────── */
const generateSql = (schema) => {
    const lines = [];
    lines.push('-- Generated by Shakti Schema Designer');
    lines.push(`-- ${new Date().toISOString()}`);
    lines.push('');
    schema.tables.forEach(t => {
        lines.push(`CREATE TABLE ${t.name} (`);
        const colLines = t.columns.map(c => {
            const parts = [`    ${c.name}`, c.type];
            if (c.pk) parts.push('PRIMARY KEY');
            if (c.nn && !c.pk) parts.push('NOT NULL');
            if (c.uq && !c.pk) parts.push('UNIQUE');
            return parts.join(' ');
        });
        const relLines = schema.relations
            .filter(r => r.fromTable === t.id)
            .map(r => {
                const fromCol = t.columns.find(c => c.id === r.fromColumn);
                const toTable = schema.tables.find(x => x.id === r.toTable);
                const toCol = toTable?.columns.find(c => c.id === r.toColumn);
                if (!fromCol || !toTable || !toCol) return null;
                return `    FOREIGN KEY (${fromCol.name}) REFERENCES ${toTable.name}(${toCol.name}) ON DELETE ${r.onDelete}`;
            })
            .filter(Boolean);
        lines.push([...colLines, ...relLines].join(',\n'));
        lines.push(');');
        lines.push('');
    });
    return lines.join('\n');
};

/* ─── Geometry ────────────────────────────────────────── */
const ROW_HEIGHT = 30;
const HEADER_HEIGHT = 42;
const TABLE_WIDTH = 260;
const MIN_TABLE_WIDTH = 200;
const MAX_TABLE_WIDTH = 640;

const tableW = (t) => t.width || TABLE_WIDTH;

const getPortPos = (schema, tableId, columnId, side = 'right') => {
    const table = schema.tables.find(t => t.id === tableId);
    if (!table) return { x: 0, y: 0 };
    const idx = table.columns.findIndex(c => c.id === columnId);
    if (idx < 0) return { x: table.x, y: table.y };
    const y = table.y + HEADER_HEIGHT + idx * ROW_HEIGHT + ROW_HEIGHT / 2;
    const x = side === 'right' ? table.x + tableW(table) : table.x;
    return { x, y };
};

const curvePath = (from, to) => {
    const dx = Math.max(60, Math.abs(to.x - from.x) / 2);
    const c1x = from.x + (from.x <= to.x ? dx : -dx);
    const c2x = to.x + (to.x <= from.x ? dx : -dx);
    return `M ${from.x} ${from.y} C ${c1x} ${from.y}, ${c2x} ${to.y}, ${to.x} ${to.y}`;
};

/* ═════════════════════════════════════════════════════════
   SCHEMA DESIGNER
   ═════════════════════════════════════════════════════════ */
const SchemaDesigner = () => {
    const [schema, setSchema] = useState(loadSchema);
    const [selectedTableId, setSelectedTableId] = useState(null);
    const [linkSource, setLinkSource] = useState(null); // { tableId, columnId }
    const [drawerOpen, setDrawerOpen] = useState('sql'); // 'sql' | 'json' | 'ai' | null
    const [toast, setToast] = useState(null);

    // Arrow (annotation) drawing mode
    const [arrowMode, setArrowMode] = useState(false);
    const [arrowSource, setArrowSource] = useState(null); // { kind, id }

    // AI chat
    const [aiKey, setAiKey] = useState(() => {
        try { return localStorage.getItem(AI_KEY_STORAGE) || ''; } catch { return ''; }
    });
    const [aiModel, setAiModel] = useState(() => {
        try { return localStorage.getItem(AI_MODEL_STORAGE) || DEFAULT_AI_MODEL; } catch { return DEFAULT_AI_MODEL; }
    });
    const [aiMessages, setAiMessages] = useState([]);
    const [aiInput, setAiInput] = useState('');
    const [aiBusy, setAiBusy] = useState(false);

    const canvasRef = useRef(null);
    const dragRef = useRef(null);
    const resizeRef = useRef(null);
    const panRef = useRef({ x: 0, y: 0, panning: false, startX: 0, startY: 0, origX: 0, origY: 0 });
    const [pan, setPan] = useState({ x: 0, y: 0 });

    /* persistence */
    useEffect(() => {
        try { localStorage.setItem(STORAGE_KEY, JSON.stringify(schema)); } catch { /* ignore */ }
    }, [schema]);

    const flash = (msg) => {
        setToast(msg);
        setTimeout(() => setToast(null), 2200);
    };

    /* ── Table actions ── */
    const addTable = () => {
        const base = { x: 120 - pan.x, y: 120 - pan.y };
        const t = {
            id: `t_${uid()}`,
            name: `table_${schema.tables.length + 1}`,
            x: base.x + (schema.tables.length * 24),
            y: base.y + (schema.tables.length * 24),
            color: '#1f1f1f',
            columns: [
                { id: `c_${uid()}`, name: 'id', type: 'UUID', pk: true, nn: true, uq: true },
            ],
        };
        setSchema(s => ({ ...s, tables: [...s.tables, t] }));
        setSelectedTableId(t.id);
    };

    const deleteTable = (tableId) => {
        setSchema(s => ({
            ...s,
            tables: s.tables.filter(t => t.id !== tableId),
            relations: s.relations.filter(r => r.fromTable !== tableId && r.toTable !== tableId),
            arrows: (s.arrows || []).filter(a =>
                !(a.from.kind === 'table' && a.from.id === tableId) &&
                !(a.to.kind === 'table' && a.to.id === tableId)
            ),
        }));
        if (selectedTableId === tableId) setSelectedTableId(null);
    };

    const updateTable = (tableId, patch) => {
        setSchema(s => ({
            ...s,
            tables: s.tables.map(t => (t.id === tableId ? { ...t, ...patch } : t)),
        }));
    };

    const addColumn = (tableId) => {
        setSchema(s => ({
            ...s,
            tables: s.tables.map(t =>
                t.id === tableId ? { ...t, columns: [...t.columns, defaultColumn()] } : t
            ),
        }));
    };

    const updateColumn = (tableId, columnId, patch) => {
        setSchema(s => ({
            ...s,
            tables: s.tables.map(t =>
                t.id === tableId
                    ? {
                        ...t,
                        columns: t.columns.map(c => (c.id === columnId ? { ...c, ...patch } : c)),
                    }
                    : t
            ),
        }));
    };

    const deleteColumn = (tableId, columnId) => {
        setSchema(s => ({
            ...s,
            tables: s.tables.map(t =>
                t.id === tableId
                    ? { ...t, columns: t.columns.filter(c => c.id !== columnId) }
                    : t
            ),
            relations: s.relations.filter(
                r =>
                    !(r.fromTable === tableId && r.fromColumn === columnId) &&
                    !(r.toTable === tableId && r.toColumn === columnId)
            ),
        }));
    };

    /* ── Notes ── */
    const addNote = () => {
        const n = {
            id: `n_${uid()}`,
            x: 140 - pan.x + (schema.notes.length * 18),
            y: 300 - pan.y + (schema.notes.length * 18),
            width: 220,
            height: 140,
            text: '',
            color: NOTE_COLORS[schema.notes.length % NOTE_COLORS.length],
        };
        setSchema(s => ({ ...s, notes: [...(s.notes || []), n] }));
    };
    const updateNote = (id, patch) => {
        setSchema(s => ({
            ...s,
            notes: (s.notes || []).map(n => n.id === id ? { ...n, ...patch } : n),
        }));
    };
    const deleteNote = (id) => {
        setSchema(s => ({
            ...s,
            notes: (s.notes || []).filter(n => n.id !== id),
            arrows: (s.arrows || []).filter(a =>
                !(a.from.kind === 'note' && a.from.id === id) &&
                !(a.to.kind === 'note' && a.to.id === id)
            ),
        }));
    };

    /* ── Arrows (annotation) ── */
    const toggleArrowMode = () => {
        setArrowMode(m => !m);
        setArrowSource(null);
        setLinkSource(null);
    };
    const handleArrowClick = (kind, id) => {
        if (!arrowMode) return false;
        if (!arrowSource) {
            setArrowSource({ kind, id });
            return true;
        }
        if (arrowSource.kind === kind && arrowSource.id === id) {
            setArrowSource(null);
            return true;
        }
        const arrow = {
            id: `a_${uid()}`,
            from: arrowSource,
            to: { kind, id },
            label: '',
        };
        setSchema(s => ({ ...s, arrows: [...(s.arrows || []), arrow] }));
        setArrowSource(null);
        setArrowMode(false);
        flash('Arrow added');
        return true;
    };
    const deleteArrow = (id) => {
        setSchema(s => ({ ...s, arrows: (s.arrows || []).filter(a => a.id !== id) }));
    };
    const updateArrow = (id, patch) => {
        setSchema(s => ({
            ...s,
            arrows: (s.arrows || []).map(a => a.id === id ? { ...a, ...patch } : a),
        }));
    };

    /* ── AI chat ── */
    const saveAiKey = (k) => {
        setAiKey(k);
        try { localStorage.setItem(AI_KEY_STORAGE, k); } catch { /* ignore */ }
    };
    const saveAiModel = (m) => {
        setAiModel(m);
        try { localStorage.setItem(AI_MODEL_STORAGE, m); } catch { /* ignore */ }
    };
    const sendAiMessage = async () => {
        const text = aiInput.trim();
        if (!text || aiBusy) return;
        if (!aiKey) {
            flash('Set your OpenRouter API key first');
            return;
        }
        const userMsg = { role: 'user', content: text };
        const history = [...aiMessages, userMsg];
        setAiMessages(history);
        setAiInput('');
        setAiBusy(true);
        try {
            const systemPrompt = `You are a senior database architect reviewing a schema in real time.
The user is designing a Postgres schema in a visual designer. You will be given the current
schema as JSON (tables, columns, relations, notes, arrows) on every turn. Give concise,
actionable feedback: normalization issues, missing indexes, naming inconsistencies, risky
types, missing FKs, missing timestamps/soft-delete, security concerns. Prefer bullet points.
When suggesting SQL, wrap it in triple backticks. Keep responses under ~250 words unless
asked to expand.`;
            const schemaContext = `Current schema JSON:\n\`\`\`json\n${JSON.stringify(schema, null, 2)}\n\`\`\``;
            const messages = [
                { role: 'system', content: systemPrompt },
                { role: 'system', content: schemaContext },
                ...history,
            ];
            const res = await fetch('https://openrouter.ai/api/v1/chat/completions', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'Authorization': `Bearer ${aiKey}`,
                    'HTTP-Referer': window.location.origin,
                    'X-Title': 'Shakti Schema Designer',
                },
                body: JSON.stringify({
                    model: aiModel,
                    messages,
                    temperature: 0.3,
                }),
            });
            if (!res.ok) {
                const errText = await res.text();
                throw new Error(`${res.status}: ${errText.slice(0, 200)}`);
            }
            const data = await res.json();
            const reply = data.choices?.[0]?.message?.content || '(empty response)';
            setAiMessages(m => [...m, { role: 'assistant', content: reply }]);
        } catch (err) {
            setAiMessages(m => [...m, { role: 'assistant', content: `⚠ Error: ${err.message}`, error: true }]);
        } finally {
            setAiBusy(false);
        }
    };
    const clearAiChat = () => setAiMessages([]);

    /* ── Relations ── */
    const startLink = (tableId, columnId) => {
        if (linkSource && linkSource.tableId === tableId && linkSource.columnId === columnId) {
            setLinkSource(null);
            return;
        }
        if (linkSource) {
            // complete
            if (linkSource.tableId === tableId && linkSource.columnId === columnId) {
                setLinkSource(null);
                return;
            }
            const rel = {
                id: `r_${uid()}`,
                fromTable: linkSource.tableId,
                fromColumn: linkSource.columnId,
                toTable: tableId,
                toColumn: columnId,
                onDelete: 'CASCADE',
            };
            setSchema(s => ({ ...s, relations: [...s.relations, rel] }));
            setLinkSource(null);
            flash('Relationship created');
        } else {
            setLinkSource({ tableId, columnId });
        }
    };

    const deleteRelation = (relId) => {
        setSchema(s => ({ ...s, relations: s.relations.filter(r => r.id !== relId) }));
    };

    /* ── Drag tables ── */
    const onTableMouseDown = (e, tableId) => {
        if (e.target.closest('.sd-no-drag')) return;
        if (arrowMode) {
            e.preventDefault();
            handleArrowClick('table', tableId);
            return;
        }
        const table = schema.tables.find(t => t.id === tableId);
        if (!table) return;
        dragRef.current = {
            kind: 'table',
            tableId,
            startX: e.clientX,
            startY: e.clientY,
            origX: table.x,
            origY: table.y,
        };
        setSelectedTableId(tableId);
        e.preventDefault();
    };

    useEffect(() => {
        const onMove = (e) => {
            // table/note resize (takes priority)
            if (resizeRef.current) {
                const r = resizeRef.current;
                if (r.kind === 'note') {
                    const nw = Math.max(140, r.origW + (e.clientX - r.startX));
                    const nh = Math.max(80, r.origH + (e.clientY - r.startY));
                    updateNote(r.id, { width: nw, height: nh });
                } else {
                    const nw = Math.min(
                        MAX_TABLE_WIDTH,
                        Math.max(MIN_TABLE_WIDTH, r.origW + (e.clientX - r.startX))
                    );
                    updateTable(r.tableId, { width: nw });
                }
                return;
            }
            // element drag (table or note)
            if (dragRef.current) {
                const d = dragRef.current;
                const nx = d.origX + (e.clientX - d.startX);
                const ny = d.origY + (e.clientY - d.startY);
                if (d.kind === 'note') {
                    updateNote(d.id, { x: nx, y: ny });
                } else {
                    updateTable(d.tableId, { x: nx, y: ny });
                }
            }
            // canvas pan
            if (panRef.current.panning) {
                const p = panRef.current;
                setPan({
                    x: p.origX + (e.clientX - p.startX),
                    y: p.origY + (e.clientY - p.startY),
                });
            }
        };
        const onUp = () => {
            dragRef.current = null;
            resizeRef.current = null;
            panRef.current.panning = false;
        };
        window.addEventListener('mousemove', onMove);
        window.addEventListener('mouseup', onUp);
        return () => {
            window.removeEventListener('mousemove', onMove);
            window.removeEventListener('mouseup', onUp);
        };
    }, []);

    const onCanvasMouseDown = (e) => {
        if (e.target !== canvasRef.current && !e.target.classList.contains('sd-grid')) return;
        setSelectedTableId(null);
        setLinkSource(null);
        panRef.current = {
            panning: true,
            startX: e.clientX,
            startY: e.clientY,
            origX: pan.x,
            origY: pan.y,
        };
    };

    /* ── Export / Import / Clear ── */
    const sqlOutput = useMemo(() => generateSql(schema), [schema]);
    const jsonOutput = useMemo(() => JSON.stringify(schema, null, 2), [schema]);

    const copyToClipboard = async (text, label) => {
        try {
            await navigator.clipboard.writeText(text);
            flash(`${label} copied`);
        } catch {
            flash('Copy failed');
        }
    };

    const downloadFile = (content, filename, mime) => {
        const blob = new Blob([content], { type: mime });
        const url = URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
    };

    const importJson = (e) => {
        const file = e.target.files?.[0];
        if (!file) return;
        const reader = new FileReader();
        reader.onload = (evt) => {
            try {
                const parsed = JSON.parse(evt.target.result);
                if (!parsed.tables || !parsed.relations) throw new Error('Invalid schema');
                setSchema(parsed);
                flash('Schema imported');
            } catch (err) {
                flash(`Import failed: ${err.message}`);
            }
        };
        reader.readAsText(file);
        e.target.value = '';
    };

    const clearAll = () => {
        if (window.confirm('Clear entire schema? This cannot be undone.')) {
            setSchema({ tables: [], relations: [], notes: [], arrows: [] });
            flash('Cleared');
        }
    };

    const resetToSeed = () => {
        if (window.confirm('Reset to seed example?')) {
            setSchema(seedSchema());
            flash('Reset to seed');
        }
    };

    const autoLayout = () => {
        const cols = 3;
        const gapX = TABLE_WIDTH + 80;
        const gapY = 360;
        setSchema(s => ({
            ...s,
            tables: s.tables.map((t, i) => ({
                ...t,
                x: 60 + (i % cols) * gapX,
                y: 60 + Math.floor(i / cols) * gapY,
            })),
        }));
        setPan({ x: 0, y: 0 });
    };

    /* ── Render helpers ── */
    const selectedTable = schema.tables.find(t => t.id === selectedTableId);

    return (
        <div className="sd-root">
            {/* Top toolbar */}
            <div className="sd-toolbar">
                <div className="sd-toolbar-left">
                    <div className="sd-brand">
                        <Database size={15} />
                        <span>Schema Designer</span>
                        <span className="sd-brand-tag">dev</span>
                    </div>
                    <div className="sd-toolbar-divider" />
                    <button className="sd-btn" onClick={addTable}>
                        <Plus size={13} /> Table
                    </button>
                    <button className="sd-btn" onClick={addNote}>
                        <StickyNote size={13} /> Note
                    </button>
                    <button
                        className={`sd-btn ${arrowMode ? 'sd-btn-active' : ''}`}
                        onClick={toggleArrowMode}
                        title="Click two elements to draw an arrow"
                    >
                        <ArrowRight size={13} /> Arrow
                    </button>
                    <button className="sd-btn" onClick={autoLayout} title="Auto arrange">
                        <LayoutGrid size={13} /> Layout
                    </button>
                </div>
                <div className="sd-toolbar-right">
                    <button
                        className={`sd-btn sd-btn-ai ${drawerOpen === 'ai' ? 'sd-btn-active' : ''}`}
                        onClick={() => setDrawerOpen(drawerOpen === 'ai' ? null : 'ai')}
                        title="AI review"
                    >
                        <Sparkles size={13} /> AI Review
                    </button>
                    <button
                        className={`sd-btn ${drawerOpen === 'sql' ? 'sd-btn-active' : ''}`}
                        onClick={() => setDrawerOpen(drawerOpen === 'sql' ? null : 'sql')}
                    >
                        <FileCode size={13} /> SQL
                    </button>
                    <button
                        className={`sd-btn ${drawerOpen === 'json' ? 'sd-btn-active' : ''}`}
                        onClick={() => setDrawerOpen(drawerOpen === 'json' ? null : 'json')}
                    >
                        <FileJson size={13} /> JSON
                    </button>
                    <div className="sd-toolbar-divider" />
                    <label className="sd-btn" style={{ cursor: 'pointer' }}>
                        <Upload size={13} /> Import
                        <input type="file" accept=".json" onChange={importJson} style={{ display: 'none' }} />
                    </label>
                    <button className="sd-btn" onClick={() => downloadFile(jsonOutput, 'schema.json', 'application/json')}>
                        <Save size={13} /> Save
                    </button>
                    <div className="sd-toolbar-divider" />
                    <button className="sd-btn sd-btn-ghost" onClick={resetToSeed} title="Reset to example">
                        <RotateCcw size={13} />
                    </button>
                    <button className="sd-btn sd-btn-danger" onClick={clearAll} title="Clear all">
                        <Trash2 size={13} />
                    </button>
                </div>
            </div>

            {/* Main area */}
            <div className="sd-body">
                {/* Canvas */}
                <div
                    ref={canvasRef}
                    className="sd-canvas"
                    onMouseDown={onCanvasMouseDown}
                >
                    <div className="sd-grid" />
                    <div
                        className="sd-viewport"
                        style={{ transform: `translate(${pan.x}px, ${pan.y}px)` }}
                    >
                        {/* Relationship lines */}
                        <svg className="sd-svg" width="4000" height="4000">
                            <defs>
                                <marker id="sd-arrowhead" viewBox="0 0 10 10" refX="9" refY="5"
                                    markerWidth="7" markerHeight="7" orient="auto-start-reverse">
                                    <path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" />
                                </marker>
                            </defs>
                            {schema.relations.map(r => {
                                const fromTable = schema.tables.find(t => t.id === r.fromTable);
                                const toTable = schema.tables.find(t => t.id === r.toTable);
                                if (!fromTable || !toTable) return null;
                                const fromRight = fromTable.x + TABLE_WIDTH / 2 < toTable.x + TABLE_WIDTH / 2;
                                const from = getPortPos(schema, r.fromTable, r.fromColumn, fromRight ? 'right' : 'left');
                                const to = getPortPos(schema, r.toTable, r.toColumn, fromRight ? 'left' : 'right');
                                return (
                                    <g key={r.id} className="sd-relation">
                                        <path d={curvePath(from, to)} className="sd-relation-path" />
                                        <circle cx={from.x} cy={from.y} r="4" className="sd-relation-dot" />
                                        <circle cx={to.x} cy={to.y} r="4" className="sd-relation-dot" />
                                        <foreignObject
                                            x={(from.x + to.x) / 2 - 12}
                                            y={(from.y + to.y) / 2 - 12}
                                            width="24"
                                            height="24"
                                        >
                                            <button
                                                className="sd-relation-delete"
                                                onClick={(e) => { e.stopPropagation(); deleteRelation(r.id); }}
                                                title="Delete relationship"
                                            >
                                                <X size={10} />
                                            </button>
                                        </foreignObject>
                                    </g>
                                );
                            })}
                            {/* Ghost line while linking */}
                            {linkSource && (
                                <path
                                    className="sd-relation-path sd-relation-ghost"
                                    d={curvePath(
                                        getPortPos(schema, linkSource.tableId, linkSource.columnId, 'right'),
                                        getPortPos(schema, linkSource.tableId, linkSource.columnId, 'right')
                                    )}
                                />
                            )}
                            {/* Annotation arrows */}
                            {(schema.arrows || []).map(a => {
                                const from = elementAnchor(schema, a.from.kind, a.from.id);
                                const to = elementAnchor(schema, a.to.kind, a.to.id);
                                if (!from || !to) return null;
                                const midX = (from.x + to.x) / 2;
                                const midY = (from.y + to.y) / 2;
                                return (
                                    <g key={a.id} className="sd-arrow">
                                        <path
                                            d={curvePath(from, to)}
                                            className="sd-arrow-path"
                                            markerEnd="url(#sd-arrowhead)"
                                        />
                                        <foreignObject x={midX - 70} y={midY - 14} width="140" height="28">
                                            <div className="sd-arrow-label-wrap">
                                                <input
                                                    className="sd-arrow-label"
                                                    placeholder="label"
                                                    value={a.label || ''}
                                                    onChange={(e) => updateArrow(a.id, { label: e.target.value })}
                                                />
                                                <button
                                                    className="sd-arrow-del"
                                                    onClick={() => deleteArrow(a.id)}
                                                    title="Delete arrow"
                                                >
                                                    <X size={10} />
                                                </button>
                                            </div>
                                        </foreignObject>
                                    </g>
                                );
                            })}
                        </svg>

                        {/* Tables */}
                        {schema.tables.map(t => (
                            <div
                                key={t.id}
                                className={`sd-table ${selectedTableId === t.id ? 'sd-table-selected' : ''}`}
                                style={{ left: t.x, top: t.y, width: tableW(t), borderTopColor: t.color }}
                                onMouseDown={(e) => onTableMouseDown(e, t.id)}
                            >
                                <div className="sd-table-head">
                                    <input
                                        className="sd-no-drag sd-table-name"
                                        value={t.name}
                                        onChange={(e) => updateTable(t.id, { name: e.target.value })}
                                        spellCheck={false}
                                    />
                                    <button
                                        className="sd-no-drag sd-icon-btn sd-danger"
                                        onClick={() => deleteTable(t.id)}
                                        title="Delete table"
                                    >
                                        <Trash2 size={11} />
                                    </button>
                                </div>
                                <div className="sd-rows">
                                    {t.columns.map(c => {
                                        const isLinkSource = linkSource?.tableId === t.id && linkSource?.columnId === c.id;
                                        const hasRelFrom = schema.relations.some(r => r.fromTable === t.id && r.fromColumn === c.id);
                                        const hasRelTo = schema.relations.some(r => r.toTable === t.id && r.toColumn === c.id);
                                        return (
                                            <div
                                                key={c.id}
                                                className={`sd-row ${isLinkSource ? 'sd-row-linking' : ''}`}
                                            >
                                                <div className={`sd-port sd-port-left ${hasRelTo ? 'sd-port-on' : ''}`} />
                                                <div className="sd-row-left sd-no-drag">
                                                    {c.pk && <Key size={10} className="sd-key" />}
                                                    <input
                                                        className="sd-col-name"
                                                        value={c.name}
                                                        onChange={(e) => updateColumn(t.id, c.id, { name: e.target.value })}
                                                        spellCheck={false}
                                                    />
                                                </div>
                                                <div className="sd-row-right sd-no-drag">
                                                    <select
                                                        className="sd-col-type"
                                                        value={c.type}
                                                        onChange={(e) => updateColumn(t.id, c.id, { type: e.target.value })}
                                                    >
                                                        {TYPES.map(ty => <option key={ty} value={ty}>{ty}</option>)}
                                                    </select>
                                                    <button
                                                        className={`sd-flag ${c.pk ? 'sd-flag-on' : ''}`}
                                                        onClick={() => updateColumn(t.id, c.id, { pk: !c.pk, nn: !c.pk || c.nn, uq: !c.pk || c.uq })}
                                                        title="Primary key"
                                                    >PK</button>
                                                    <button
                                                        className={`sd-flag ${c.nn ? 'sd-flag-on' : ''}`}
                                                        onClick={() => updateColumn(t.id, c.id, { nn: !c.nn })}
                                                        title="Not null"
                                                    >NN</button>
                                                    <button
                                                        className={`sd-flag ${c.uq ? 'sd-flag-on' : ''}`}
                                                        onClick={() => updateColumn(t.id, c.id, { uq: !c.uq })}
                                                        title="Unique"
                                                    >UQ</button>
                                                    <button
                                                        className={`sd-flag sd-flag-link ${isLinkSource ? 'sd-flag-on' : ''}`}
                                                        onClick={() => startLink(t.id, c.id)}
                                                        title={linkSource ? 'Click to connect' : 'Start relation from this column'}
                                                    >
                                                        <Link2 size={10} />
                                                    </button>
                                                    <button
                                                        className="sd-flag sd-flag-del"
                                                        onClick={() => deleteColumn(t.id, c.id)}
                                                        title="Delete column"
                                                    >
                                                        <X size={10} />
                                                    </button>
                                                </div>
                                                <div className={`sd-port sd-port-right ${hasRelFrom ? 'sd-port-on' : ''}`} />
                                            </div>
                                        );
                                    })}
                                </div>
                                <button
                                    className="sd-no-drag sd-add-col"
                                    onClick={() => addColumn(t.id)}
                                >
                                    <Plus size={11} /> Add column
                                </button>
                                <div
                                    className="sd-no-drag sd-resize-handle"
                                    title="Drag to resize"
                                    onMouseDown={(e) => {
                                        e.stopPropagation();
                                        e.preventDefault();
                                        resizeRef.current = {
                                            tableId: t.id,
                                            startX: e.clientX,
                                            origW: tableW(t),
                                        };
                                        setSelectedTableId(t.id);
                                    }}
                                />
                            </div>
                        ))}

                        {/* Comment notes */}
                        {(schema.notes || []).map(n => {
                            const isArrowSrc = arrowSource?.kind === 'note' && arrowSource?.id === n.id;
                            return (
                                <div
                                    key={n.id}
                                    className={`sd-note ${isArrowSrc ? 'sd-note-arrow-src' : ''} ${arrowMode ? 'sd-arrow-target' : ''}`}
                                    style={{
                                        left: n.x,
                                        top: n.y,
                                        width: n.width || 220,
                                        height: n.height || 140,
                                        background: n.color || NOTE_COLORS[0],
                                    }}
                                    onMouseDown={(e) => {
                                        if (e.target.closest('.sd-no-drag')) return;
                                        if (arrowMode) {
                                            e.preventDefault();
                                            handleArrowClick('note', n.id);
                                            return;
                                        }
                                        dragRef.current = {
                                            kind: 'note',
                                            id: n.id,
                                            startX: e.clientX,
                                            startY: e.clientY,
                                            origX: n.x,
                                            origY: n.y,
                                        };
                                        e.preventDefault();
                                    }}
                                >
                                    <div className="sd-note-head">
                                        <div className="sd-note-colors sd-no-drag">
                                            {NOTE_COLORS.map(col => (
                                                <button
                                                    key={col}
                                                    className={`sd-note-color ${n.color === col ? 'sd-note-color-on' : ''}`}
                                                    style={{ background: col }}
                                                    onClick={() => updateNote(n.id, { color: col })}
                                                    title="Change color"
                                                />
                                            ))}
                                        </div>
                                        <button
                                            className="sd-no-drag sd-icon-btn sd-danger"
                                            onClick={() => deleteNote(n.id)}
                                            title="Delete note"
                                        >
                                            <Trash2 size={11} />
                                        </button>
                                    </div>
                                    <textarea
                                        className="sd-no-drag sd-note-text"
                                        placeholder="Write a comment…"
                                        value={n.text}
                                        onChange={(e) => updateNote(n.id, { text: e.target.value })}
                                        spellCheck={false}
                                    />
                                    <div
                                        className="sd-no-drag sd-resize-handle"
                                        title="Drag to resize"
                                        onMouseDown={(e) => {
                                            e.stopPropagation();
                                            e.preventDefault();
                                            resizeRef.current = {
                                                kind: 'note',
                                                id: n.id,
                                                startX: e.clientX,
                                                startY: e.clientY,
                                                origW: n.width || 220,
                                                origH: n.height || 140,
                                            };
                                        }}
                                    />
                                </div>
                            );
                        })}
                    </div>

                    {/* Canvas hint */}
                    {schema.tables.length === 0 && (
                        <div className="sd-canvas-hint">
                            <Database size={36} strokeWidth={1.2} />
                            <h3>Empty canvas</h3>
                            <p>Click <strong>+ Table</strong> to begin, or <button className="sd-link" onClick={resetToSeed}>load the seed example</button>.</p>
                        </div>
                    )}

                    {/* Link-mode banner */}
                    {linkSource && (
                        <div className="sd-linking-banner">
                            <GitBranch size={12} />
                            <span>Click another column to complete the relationship</span>
                            <button onClick={() => setLinkSource(null)} className="sd-cancel-link">Cancel</button>
                        </div>
                    )}

                    {/* Arrow-mode banner */}
                    {arrowMode && (
                        <div className="sd-linking-banner">
                            <ArrowRight size={12} />
                            <span>
                                {arrowSource
                                    ? 'Click a second element to finish the arrow'
                                    : 'Click a table or note to start the arrow'}
                            </span>
                            <button onClick={toggleArrowMode} className="sd-cancel-link">Cancel</button>
                        </div>
                    )}

                    {/* Toast */}
                    {toast && <div className="sd-toast">{toast}</div>}
                </div>

                {/* Drawer */}
                {drawerOpen === 'ai' && (
                    <aside className="sd-drawer sd-drawer-ai">
                        <div className="sd-drawer-head">
                            <div className="sd-drawer-title">
                                <Sparkles size={13} />
                                <span>AI Review</span>
                            </div>
                            <div className="sd-drawer-actions">
                                <button
                                    className="sd-btn sd-btn-ghost sd-btn-sm"
                                    onClick={clearAiChat}
                                    title="Clear chat"
                                >
                                    <RotateCcw size={11} />
                                </button>
                                <button
                                    className="sd-btn sd-btn-ghost sd-btn-sm"
                                    onClick={() => setDrawerOpen(null)}
                                >
                                    <X size={11} />
                                </button>
                            </div>
                        </div>

                        <div className="sd-ai-config">
                            <div className="sd-ai-config-row">
                                <KeyRound size={11} />
                                <input
                                    type="password"
                                    className="sd-ai-input"
                                    placeholder="OpenRouter API key (sk-or-...)"
                                    value={aiKey}
                                    onChange={(e) => saveAiKey(e.target.value)}
                                    autoComplete="off"
                                />
                            </div>
                            <div className="sd-ai-config-row">
                                <select
                                    className="sd-ai-input"
                                    value={aiModel}
                                    onChange={(e) => saveAiModel(e.target.value)}
                                >
                                    <option value="openai/gpt-4o-mini">gpt-4o-mini</option>
                                    <option value="openai/gpt-4o">gpt-4o</option>
                                    <option value="anthropic/claude-3.5-sonnet">claude-3.5-sonnet</option>
                                    <option value="anthropic/claude-3.5-haiku">claude-3.5-haiku</option>
                                    <option value="google/gemini-2.0-flash-001">gemini-2.0-flash</option>
                                    <option value="meta-llama/llama-3.3-70b-instruct">llama-3.3-70b</option>
                                </select>
                            </div>
                        </div>

                        <div className="sd-ai-messages">
                            {aiMessages.length === 0 && (
                                <div className="sd-ai-empty">
                                    <Sparkles size={22} strokeWidth={1.2} />
                                    <p>Ask the AI to review your schema.</p>
                                    <div className="sd-ai-suggestions">
                                        {[
                                            'Review this schema and flag normalization issues.',
                                            'What indexes am I missing?',
                                            'Suggest missing tables for a SaaS app.',
                                            'Are the FKs and ON DELETE rules correct?',
                                        ].map(s => (
                                            <button
                                                key={s}
                                                className="sd-ai-suggestion"
                                                onClick={() => setAiInput(s)}
                                            >
                                                {s}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            )}
                            {aiMessages.map((m, i) => (
                                <div key={i} className={`sd-ai-msg sd-ai-msg-${m.role} ${m.error ? 'sd-ai-msg-error' : ''}`}>
                                    <div className="sd-ai-msg-role">{m.role === 'user' ? 'You' : 'AI'}</div>
                                    <div className="sd-ai-msg-body">{m.content}</div>
                                </div>
                            ))}
                            {aiBusy && (
                                <div className="sd-ai-msg sd-ai-msg-assistant">
                                    <div className="sd-ai-msg-role">AI</div>
                                    <div className="sd-ai-msg-body sd-ai-typing">
                                        <span /><span /><span />
                                    </div>
                                </div>
                            )}
                        </div>

                        <div className="sd-ai-composer">
                            <textarea
                                className="sd-ai-textarea"
                                placeholder={aiKey ? 'Ask about your schema… (Enter to send, Shift+Enter for new line)' : 'Paste your OpenRouter API key above first'}
                                value={aiInput}
                                onChange={(e) => setAiInput(e.target.value)}
                                onKeyDown={(e) => {
                                    if (e.key === 'Enter' && !e.shiftKey) {
                                        e.preventDefault();
                                        sendAiMessage();
                                    }
                                }}
                                rows={2}
                                disabled={aiBusy}
                            />
                            <button
                                className="sd-btn sd-btn-ai"
                                onClick={sendAiMessage}
                                disabled={aiBusy || !aiInput.trim()}
                            >
                                <Send size={12} />
                            </button>
                        </div>
                    </aside>
                )}

                {/* Drawer (SQL/JSON) */}
                {(drawerOpen === 'sql' || drawerOpen === 'json') && (
                    <aside className="sd-drawer">
                        <div className="sd-drawer-head">
                            <div className="sd-drawer-title">
                                {drawerOpen === 'sql' ? <FileCode size={13} /> : <FileJson size={13} />}
                                <span>{drawerOpen === 'sql' ? 'SQL Preview' : 'JSON Schema'}</span>
                            </div>
                            <div className="sd-drawer-actions">
                                <button
                                    className="sd-btn sd-btn-sm"
                                    onClick={() => copyToClipboard(
                                        drawerOpen === 'sql' ? sqlOutput : jsonOutput,
                                        drawerOpen === 'sql' ? 'SQL' : 'JSON'
                                    )}
                                >
                                    <Copy size={11} /> Copy
                                </button>
                                <button
                                    className="sd-btn sd-btn-sm"
                                    onClick={() => downloadFile(
                                        drawerOpen === 'sql' ? sqlOutput : jsonOutput,
                                        drawerOpen === 'sql' ? 'schema.sql' : 'schema.json',
                                        drawerOpen === 'sql' ? 'text/plain' : 'application/json'
                                    )}
                                >
                                    <Download size={11} /> Save
                                </button>
                                <button
                                    className="sd-btn sd-btn-ghost sd-btn-sm"
                                    onClick={() => setDrawerOpen(null)}
                                >
                                    <X size={11} />
                                </button>
                            </div>
                        </div>
                        <pre className="sd-drawer-code">
                            {drawerOpen === 'sql' ? sqlOutput : jsonOutput}
                        </pre>
                    </aside>
                )}
            </div>

            {/* Status bar */}
            <div className="sd-statusbar">
                <span><MousePointer2 size={11} /> Drag tables · drag canvas to pan</span>
                <span>·</span>
                <span>{schema.tables.length} tables</span>
                <span>·</span>
                <span>{schema.relations.length} relations</span>
                <span>·</span>
                <span>{(schema.notes || []).length} notes</span>
                <span>·</span>
                <span>{(schema.arrows || []).length} arrows</span>
                <span>·</span>
                <span>{schema.tables.reduce((a, t) => a + t.columns.length, 0)} columns</span>
                <span style={{ marginLeft: 'auto' }}>
                    {selectedTable ? `Selected: ${selectedTable.name}` : 'No selection'}
                </span>
            </div>
        </div>
    );
};

export default SchemaDesigner;
